### PR TITLE
Dishes/main page

### PR DESCRIPTION
**Pull request by Philippoes**
## Pivotal Tracker story 

https://www.pivotaltracker.com/story/show/139182543

## Changes proposed in this pull request:

Connects the dishes api endpoint with a main/dish page on the mobile app

## What I have learned working on this feature:

• Practiced how query works and how you can set up a factory to send requests and receive responses
• That camelCase should be used in controller names
• Better overall understanding of ionic and angularJS 

screen shot 2017-02-08 at 18 45 59

### CODE REVIEW

**Review by diraulo — CHANGES_REQUESTED** [review]
`lib/*` shouldn't be tracked by version control

**Comment by Philippoes** [comment]
@diraulo that should have been added on set up, i pulled from develop and i assumed that everything was added to gitignore :)

Lib is already on devlop,

**Comment by tochman** [comment]
You need to remove lib from git

**Comment by Philippoes** [comment]
@diraulo @tochman done :)

**Review by tochman — APPROVED** [review]

**Review by diraulo — APPROVED** [review]

**Pull request merged**
